FROM ubuntu

#  update 
RUN apt-get update

# intall vim
RUN apt-get install -y vim

#  install  git
RUN apt-get install -y git

#  install  goland
RUN apt-get install -y golang

# install clibs
#RUN apt-get install build-base gcc abuild binutils binutils-doc gcc-doc


# basic setup
RUN mkdir -p /opt/gocode

ENV GOROOT=/usr/lib/go
ENV GOPATH=/opt/gocode

# install gorilla
RUN go get -u github.com/gorilla/mux

#install gozmq3
RUN go get github.com/pebbe/zmq3

#copy the zmq library
COPY zmq /katomic/zmq

# environments
ENV PATH=$GOROOT/bin:$GOPATH/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:

#installing ZMQ 
RUN cd /katomic/zmq && tar -xvf zeromq-3.2.5.tar && cd  /katomic/zmq/zeromq-3.2.5 && ./configure && make && make install

#installing CZMQ
RUN cd /katomic/zmq && tar -xvf czmq-3.0.2.tar &&  cd /katomic/zmq/czmq-3.0.2 && ./configure && make && make install
 
#install zmq3 binding for go
RUN go get github.com/pebbe/zmq3

